### ISSUE TITLE
存证示例代码bug

### ISSUE THREAD

**Issue by hoi-lau** [cryptape/appchainj#172]
ConvertStrByte.stringToHexString(content);
这个方法不支持中文字符串呀;
https://github.com/citahub/cita-sdk-java/blob/develop/tests/src/test/java/com/citahub/cita/tests/StoreRecordTest.java

**Comment by UDLD** [comment]
@imLiukai   develop分支上ConvertStrByte.stringToHexString(content)已支持中文，只是还没发版
